#!/bin/sh
set -e

echo "=== Docker Entrypoint Starting ==="
echo "BMP_URL environment variable: $BMP_URL"

# Inject BMP_URL environment variable into HTML
if [ -n "$BMP_URL" ]; then
    echo "Injecting BMP_URL: $BMP_URL"
    
    # Write runtime env.js for the frontend to read
    cat > /usr/share/nginx/html/env.js << EOF
// Auto-generated by Docker entrypoint
window.BMP_URL = "$BMP_URL";
console.log("env.js loaded with BMP_URL:", window.BMP_URL);
EOF
    
    echo "env.js content:"
    cat /usr/share/nginx/html/env.js
    
    # Also update meta tag in HTML
    sed -i "s|<!-- <meta name=\"bmp-url\" content=\"REPLACE_WITH_ENV_VAR\"> -->|<meta name=\"bmp-url\" content=\"$BMP_URL\">|g" /usr/share/nginx/html/index.html
    
    # Also update config.json as fallback
    cat > /usr/share/nginx/html/config.json << EOF
{"BMP_URL": "$BMP_URL"}
EOF
    
    echo "=== Injection Complete ==="
else
    echo "WARNING: BMP_URL is not set. Using existing config.json/env.js."
fi

echo "=== Starting nginx ==="

# Execute the CMD
exec "$@"
